# Multi-stage build to download Kafka SPI
FROM alpine:latest as downloader
RUN apk add --no-cache curl
RUN curl -L -o /keycloak-kafka-1.3.0.jar \
    https://github.com/SnuK87/keycloak-kafka/releases/download/1.3.0/keycloak-kafka-1.3.0-jar-with-dependencies.jar
RUN curl -L -o /keycloak-home-idp-discovery.jar \
    https://github.com/sventorben/keycloak-home-idp-discovery/releases/download/v26.2.1/keycloak-home-idp-discovery.jar

# Custom Keycloak with Kafka SPI and Home IdP Discovery SPI
FROM quay.io/keycloak/keycloak:26.6.3

# Copy the downloaded JARs from the previous stage
COPY --from=downloader /keycloak-kafka-1.3.0.jar /opt/keycloak/providers/
COPY --from=downloader /keycloak-home-idp-discovery.jar /opt/keycloak/providers/

# Build Keycloak with the new provider
# RUN /opt/keycloak/bin/kc.sh build

# Set the entrypoint
ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]